= LeoCode - Interface Documentation
Keintzel Florian, Ablinger Raphael, Sugic Oliver
1.0.1, 2022-01-25: Leocode
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== HTML-FORM -> Quarkus-Backend:
    Die Parameter und Dateien werden vom Html-Form über
    MultipartFormDataInput zum Quarkus-Backend geschickt.
    Files werden dan in Datenbank gespeichert
    Und zuletzt wird das Abgegebene Projekt und die für das
    Testen benötigten Files in dem "project-under-test" gespeichert.

== Leocode-Backend->Testing-API:
Über Kafka wird die Abgabe an die Testing API geschickt.
Genauer wird die Abgabe über den "submission-input" channel weitergeschickt
In der Testing-API wird es dann für Jenkins vorbereitet und dann damit auch
weitergegeben.

== Testing-API -> Jenkins:
Es wird einfach in der FileHandler Klasse ein Script
ausgeführt, dass den Jenkins started und das dann auch
das ganze Projekt Tested.

== Jenkins -> Testing-API:
Das Ergebniss von den Tests wird einfach in der Submission Klasse
im result gespeichert.

== Testing-API -> Leocode-Backend:
Das Backend bekommt dann das ganze vollständig geprüfte Project über
Kafka wieder zurück.
Dies geschieht im "submission-result" channel.

== Testing-API -> Frontend:
In den Endpoints ist ebenso ein "submission-result" Anschluss worüber
er sich die Neuheiten hohlt und dann auf das Frontend gibt

== Kafka -> Testing-Api
Das Submission Objekt wird an die Testing-Api weitergeben
Testing-Api -> Kafka
Zurück kommt das Ergebnis der ausgeführten Tests von der Testing-Api

== Kafka -> Backend
Hier bekommt man das Ergebnis der Testung zurück

== Backend -> Kafka
Hier werden die wichtigen Files/Infos übergeben die man zur Testung braucht