name: GitHub Pages CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Asciidoctor Convert Action
        uses: quirinecker/asciidoctor-convert-action@1.3
        with:
          slides: true
          inputPath: input
          outputPath: output
